In [1]:
import pandas as pd

In [11]:
torneos_unidos = pd.read_csv('partidos_atp_2000_2024.csv')
torneos_unidos

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year
0,2000-301,Auckland,Hard,32,A,20000110,1,103163,1.0,NaN,...,39.0,29.0,17.0,4.0,7.0,11.0,1612.0,63.0,595.0,2000
1,2000-301,Auckland,Hard,32,A,20000110,2,102607,NaN,Q,...,25.0,18.0,12.0,3.0,6.0,211.0,157.0,49.0,723.0,2000
2,2000-301,Auckland,Hard,32,A,20000110,3,103252,NaN,NaN,...,20.0,7.0,8.0,7.0,11.0,48.0,726.0,59.0,649.0,2000
3,2000-301,Auckland,Hard,32,A,20000110,4,103507,7.0,NaN,...,29.0,14.0,10.0,6.0,8.0,45.0,768.0,61.0,616.0,2000
4,2000-301,Auckland,Hard,32,A,20000110,5,102103,NaN,Q,...,34.0,18.0,12.0,5.0,9.0,167.0,219.0,34.0,873.0,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74901,2024-M-DC-2024-WG2-PO-URU-MDA-01,Davis Cup WG2 PO: URU vs MDA,Clay,4,D,20240203,5,212051,NaN,NaN,...,17.0,7.0,6.0,8.0,14.0,1109.0,8.0,740.0,34.0,2024
74902,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,1,122533,NaN,NaN,...,25.0,6.0,9.0,1.0,4.0,554.0,67.0,748.0,32.0,2024
74903,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,2,144748,NaN,NaN,...,25.0,7.0,11.0,5.0,12.0,416.0,109.0,NaN,NaN,2024
74904,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,4,122533,NaN,NaN,...,32.0,17.0,14.0,5.0,9.0,554.0,67.0,416.0,109.0,2024
74905,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,5,202475,NaN,NaN,...,25.0,8.0,8.0,9.0,14.0,748.0,32.0,NaN,NaN,2024

In [12]:
torneos_unidos['tourney_name'] = torneos_unidos['tourney_name'].str.strip().str.lower()

In [15]:
grand_slams = torneos_unidos[torneos_unidos['tourney_name'].isin(['us open','wimbledon','roland garros','australian open'])]
grand_slams

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year
2130,2000-520,roland garros,Clay,128,G,20000529,1,101736,1.0,NaN,...,38.0,22.0,16.0,9.0,13.0,1.0,5085.0,116.0,355.0,2000
2131,2000-520,roland garros,Clay,128,G,20000529,2,102344,NaN,NaN,...,13.0,9.0,11.0,14.0,23.0,40.0,845.0,219.0,158.0,2000
2132,2000-520,roland garros,Clay,128,G,20000529,3,103181,NaN,NaN,...,65.0,15.0,23.0,12.0,25.0,88.0,463.0,83.0,494.0,2000
2133,2000-520,roland garros,Clay,128,G,20000529,4,102644,NaN,NaN,...,27.0,17.0,16.0,9.0,17.0,45.0,802.0,110.0,376.0,2000
2134,2000-520,roland garros,Clay,128,G,20000529,5,103454,NaN,NaN,...,36.0,10.0,14.0,5.0,12.0,75.0,579.0,130.0,310.0,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74139,2024-560,us open,Hard,128,G,20240826,222,126203,12.0,NaN,...,77.0,20.0,22.0,11.0,13.0,12.0,3120.0,4.0,7035.0,2024
74140,2024-560,us open,Hard,128,G,20240826,223,126207,20.0,NaN,...,53.0,22.0,18.0,8.0,14.0,20.0,2120.0,9.0,3655.0,2024
74141,2024-560,us open,Hard,128,G,20240826,224,206173,1.0,NaN,...,43.0,32.0,16.0,7.0,11.0,1.0,9360.0,25.0,1695.0,2024
74142,2024-560,us open,Hard,128,G,20240826,225,126203,12.0,NaN,...,57.0,27.0,24.0,5.0,11.0,12.0,3120.0,20.0,2120.0,2024
74143,2024-560,us open,Hard,128,G,20240826,226,206173,1.0,NaN,...,36.0,16.0,16.0,6.0,12.0,1.0,9360.0,12.0,3120.0,2024

In [7]:
players = pd.read_csv('atp_players.csv')
players

C:\Users\Usuario\AppData\Local\Temp\ipykernel_14880\4038618507.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  players = pd.read_csv('atp_players.csv')

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id
0,100001,Gardnar,Mulloy,R,19131122.0,USA,185.0,Q54544
1,100002,Pancho,Segura,R,19210620.0,ECU,168.0,Q54581
2,100003,Frank,Sedgman,R,19271002.0,AUS,180.0,Q962049
3,100004,Giuseppe,Merlo,R,19271011.0,ITA,NaN,Q1258752
4,100005,Richard,Gonzalez,R,19280509.0,USA,188.0,Q53554
...,...,...,...,...,...,...,...,...
65984,213700,Matvei,Kobiakov,U,NaN,RUS,NaN,NaN
65985,213701,Tobia Costanzo,Baragiola Mordini,U,NaN,ITA,NaN,NaN
65986,213702,Dominik,Wijntjes,U,NaN,NZL,NaN,NaN
65987,213703,Sam,Wensley,U,NaN,AUS,NaN,NaN
65988,213704,Harry,Roberts,U,NaN,AUS,NaN,NaN

In [8]:
players['full_name'] = players['name_first'] + " " + players['name_last']
players

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
0,100001,Gardnar,Mulloy,R,19131122.0,USA,185.0,Q54544,Gardnar Mulloy
1,100002,Pancho,Segura,R,19210620.0,ECU,168.0,Q54581,Pancho Segura
2,100003,Frank,Sedgman,R,19271002.0,AUS,180.0,Q962049,Frank Sedgman
3,100004,Giuseppe,Merlo,R,19271011.0,ITA,NaN,Q1258752,Giuseppe Merlo
4,100005,Richard,Gonzalez,R,19280509.0,USA,188.0,Q53554,Richard Gonzalez
...,...,...,...,...,...,...,...,...,...
65984,213700,Matvei,Kobiakov,U,NaN,RUS,NaN,NaN,Matvei Kobiakov
65985,213701,Tobia Costanzo,Baragiola Mordini,U,NaN,ITA,NaN,NaN,Tobia Costanzo Baragiola Mordini
65986,213702,Dominik,Wijntjes,U,NaN,NZL,NaN,NaN,Dominik Wijntjes
65987,213703,Sam,Wensley,U,NaN,AUS,NaN,NaN,Sam Wensley
65988,213704,Harry,Roberts,U,NaN,AUS,NaN,NaN,Harry Roberts

In [9]:
players_top10 = players[players['full_name'].isin(['Carlos Alcaraz','Jannik Sinner','Alexander Zverev','Taylor Fritz','Jack Draper','Ben Shelton','Novak Djokovic','Alex de Minaur','Holger Rune','Lorenzo Musetti'])]
players_top10

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
643,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,Alexander Zverev
4919,104925,Novak,Djokovic,R,19870522.0,SRB,188.0,Q5812,Novak Djokovic
26187,126203,Taylor,Fritz,R,19971028.0,USA,196.0,Q17660516,Taylor Fritz
58459,206173,Jannik,Sinner,R,20010816.0,ITA,191.0,Q54812588,Jannik Sinner
59804,207518,Lorenzo,Musetti,R,20020303.0,ITA,185.0,Q54813043,Lorenzo Musetti
60019,207733,Jack,Draper,L,20011222.0,GBR,193.0,Q65030599,Jack Draper
60275,207989,Carlos,Alcaraz,R,20030505.0,ESP,183.0,Q85518537,Carlos Alcaraz
60315,208029,Holger,Rune,R,20030429.0,DEN,188.0,NaN,Holger Rune
62383,210097,Ben,Shelton,L,20021009.0,USA,193.0,Q108532383,Ben Shelton

In [17]:
premios = pd.read_csv('melt premios tennis.csv')
premios

      Unnamed: 0  year             tourney key round      premio €
0              0  2000          us open - 2000     W  1.643167e+06
1              1  2001          us open - 2001     W  1.684904e+06
2              2  2002          us open - 2002     W  1.727700e+06
3              3  2003          us open - 2003     W  1.771584e+06
4              4  2004          us open - 2004     W  1.816582e+06
...          ...   ...                     ...   ...           ...
1095        1095  2020  australian open - 2020    Q1  3.165882e+04
1096        1096  2021  australian open - 2021    Q1  3.246296e+04
1097        1097  2022  australian open - 2022    Q1  3.328752e+04
1098        1098  2023  australian open - 2023    Q1  3.413302e+04
1099        1099  2024  australian open - 2024    Q1  3.500000e+04

[1100 rows x 5 columns]